# 指定基础镜像，项目依赖的jdk
FROM docker.io/openjdk:8u181-jdk
# 复制本地文件到容器
COPY /target/only-0.0.1-SNAPSHOT.jar /chatweb.jar
# 指定容器启动时执行的命令
ENTRYPOINT java -jar /chatweb.jar
# 指定于外界交互的端口
EXPOSE 80

# 运行容器命令：docker run -d -p 80:8080 --name chatweb chatweb:test
# docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=InnerConce@93 --name charweb mysql
# docker run -d -p 6379:6379 --name charwebRedis redis --requirepass "innercon"
# docker run -d -p 15672:15672 -p 5672:5672 --hostname charwebRabbit --name charwebRabbit -e RABBITMQ_DEFAULT_USER=InnerConce -e RABBITMQ_DEFAULT_PASS=innerconce rabbitmq