# 访问端口
server:
  port: 8080
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://106.12.39.122:3306/chatweb
    username: chatweb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    port: 6379
    host: 106.12.39.122
    password: innercon
  # Rabbit MQ配置
  rabbitmq:
    host: 106.12.39.122
    port: 5672
    username: InnerConce
    password: innerconce
#  mvc:
#    static-path-pattern: /intercept/**
#  resources:
#    static-locations: classpath:/intercept/

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chatweb.only.tableEntity
  global-config:
    id-type: 3
    db-column-underline: false
    field-strategy: 1
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# 日志配置
logging:
  level.root: info
  file: logs/chatweb.log