# 访问端口
server:
  port: 8080
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://106.12.73.176:3306/chatWeb
    username: chatweb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chatweb.only.tableEntity
  global-config:
    id-type: 3
    db-column-underline: false
    field-strategy: 1
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# 日志配置
logging:
  level.root: info
  file: logs/chatweb.log
